### ISSUE TITLE
Content-Disposition header set to the string 'None'

### ISSUE THREAD

**Issue by tubaman** [dailymuse/s3-content-type-fixer#6]
If your S3 object didn't have an explicit content disposition, boto returns a python None.  If you then set that on the copied S3 object, it actually sets the header value to the string 'None'.

**Comment by fmp777** [comment]
This script dead?  this going to get merged?  content disposition is still set to none

**Comment by ysimonson** [comment]
See #7. The merge conflicts weren't addressed, so I'm going to close this and the PR.
